import MainNavigation from '@/components/layout/main-navigation'
import './globals.css'
import { Inter } from 'next/font/google'
import Provider from '@/components/provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Mustafa Abboud Task',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <main>
            <MainNavigation />
            {children}
          </main>
        </Provider>
      </body>
    </html>
  )
}
